import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MobileNavigation from "@/components/web/navigation/mobile_navigation";
import DeskTopNavigation from "@/components/web/navigation/desktop_navigation";
import { SessionProvider } from "next-auth/react";
import ArticleState from "@/context/ArticlesContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <ArticleState>

    <html lang="en">
      <body className="cantata-one-regular overflow-x-hidden">
        
        {children}
        <MobileNavigation />
        </body>
    </html>
      </ArticleState>
    </SessionProvider>
  );
}
