
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MobileNavigation from "@/components/web/navigation/mobile_navigation";

import ArticleState from "@/context/ArticlesContext";
import AuthState from "@/context/AuthContext";
import FeedState from "@/context/FeedContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <AuthState>
      <ArticleState>
      <FeedState>


    <html lang="en">
      <body className="cantata-one-regular overflow-x-hidden">
        
        {children}
        <MobileNavigation />
        </body>
    </html>
      </FeedState>
      </ArticleState>
      </AuthState>
  
  );
}
